language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t 7107071070/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true 7107071070/react-test npm test

after_success:
  - docker build -t 7107071070/multi-client ./client
  - docker build -t 7107071070/multi-nginx ./nginx
  - docker build -t 7107071070/multi-server ./server
  - docker build -t 7107071070/multi-worker ./worker
